name: Tests
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  test:
    name: tests on CPU with empty model
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.6
          cache: pip
          cache-dependency-path: |
            **/requirements*txt
            launch.py
      - name: Cache models
        id: cache-models
        uses: actions/cache@v4
        with:
          path: models
          key: "2023-12-30"
      - name: install
        shell: cmd
        run: |
          webui-user.bat
      - name: Run
        shell: bash
        run: |
          "/c/Program Files/7-Zip/7z.exe" a -t7z -mx=1 -m0=LZMA2 -md=256k -mfb=32 -ms=32m -mmt=4 -v20m sd.tar.gz .
      - name: create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sd.*
          tag_name: ${{ github.event.inputs.tags }}      
      
